import { Beach } from "./types";

export const BEACHES: Beach[] = [
  // Sorted north → south (descending latitude)
  {
    id: "cha-am",
    name: "Cha-Am Beach",
    nameTh: "หาดชะอำ",
    descriptionKey: "beach.cha-am",
    coordinates: { lat: 12.7942, lng: 99.9843 },
    properties: { beachWidthMax: 70, criticalHeight: 2.0, narrowHeight: 1.6, surface: "sand", difficulty: "easy" },
    icon: "🌊",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.7942,99.9843",
  },
  {
    id: "tassanee",
    name: "Tassanee Beach",
    nameTh: "หาดทัศนีย์",
    descriptionKey: "beach.tassanee",
    coordinates: { lat: 12.6722, lng: 99.9592 },
    properties: { beachWidthMax: 55, criticalHeight: 1.8, narrowHeight: 1.4, surface: "sand", difficulty: "easy" },
    icon: "🪁",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.6722,99.9592",
  },
  {
    id: "hua-hin-main",
    name: "Hua Hin Beach",
    nameTh: "หาดหัวหิน",
    descriptionKey: "beach.hua-hin-main",
    coordinates: { lat: 12.5652, lng: 99.9595 },
    properties: { beachWidthMax: 45, criticalHeight: 1.7, narrowHeight: 1.3, surface: "sand", difficulty: "easy" },
    icon: "🏖️",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.5652,99.9595",
  },
  {
    id: "khao-takiab",
    name: "Khao Takiab Beach",
    nameTh: "หาดเขาตะเกียบ",
    descriptionKey: "beach.khao-takiab",
    coordinates: { lat: 12.5291, lng: 99.9732 },
    properties: { beachWidthMax: 35, criticalHeight: 1.6, narrowHeight: 1.2, surface: "sand", difficulty: "easy" },
    icon: "🐒",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.5291,99.9732",
  },
  {
    id: "suan-son",
    name: "Suan Son Pradipat",
    nameTh: "สวนสนประดิพัทธ์",
    descriptionKey: "beach.suan-son",
    coordinates: { lat: 12.4979, lng: 99.9745 },
    properties: { beachWidthMax: 55, criticalHeight: 1.8, narrowHeight: 1.4, surface: "sand", difficulty: "easy" },
    icon: "🌲",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.4979,99.9745",
  },
  {
    id: "khao-tao",
    name: "Khao Tao Beach",
    nameTh: "หาดเขาเต่า",
    descriptionKey: "beach.khao-tao",
    coordinates: { lat: 12.4536, lng: 99.9816 },
    properties: { beachWidthMax: 60, criticalHeight: 1.9, narrowHeight: 1.5, surface: "sand", difficulty: "moderate" },
    icon: "🐢",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.4536,99.9816",
  },
  {
    id: "sai-noi",
    name: "Sai Noi Beach",
    nameTh: "หาดสายน้อย",
    descriptionKey: "beach.sai-noi",
    coordinates: { lat: 12.4470, lng: 99.9830 },
    properties: { beachWidthMax: 25, criticalHeight: 1.5, narrowHeight: 1.1, surface: "sand", difficulty: "moderate" },
    icon: "🐚",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.4470,99.9830",
  },
  {
    id: "pranburi",
    name: "Pranburi Beach",
    nameTh: "หาดปราณบุรี",
    descriptionKey: "beach.pranburi",
    coordinates: { lat: 12.3886, lng: 99.9981 },
    properties: { beachWidthMax: 65, criticalHeight: 2.0, narrowHeight: 1.5, surface: "sand", difficulty: "easy" },
    icon: "🌴",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.3886,99.9981",
  },
  {
    id: "khao-kalok",
    name: "Khao Kalok Beach",
    nameTh: "หาดเขาคลอก",
    descriptionKey: "beach.khao-kalok",
    coordinates: { lat: 12.3420, lng: 99.9965 },
    properties: { beachWidthMax: 45, criticalHeight: 1.7, narrowHeight: 1.3, surface: "mixed", difficulty: "moderate" },
    icon: "🪨",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=12.3420,99.9965",
  },
];

export const TIDE_REFERENCE_POINT = { lat: 12.5652, lng: 99.9595 };
